version: '3.3'
services:
    grafana:
        image: grafana/grafana
        volumes:
            - grafana-volume:/var/lib/grafana
        ports:
            - 3000:3000
        links:
            - influxdb

    influxdb:
        image: tutum/influxdb
        volumes:
            - influxdb-volume:/data
        ports:
            - 8083:8083
            - 8086:8086
    gathering:
        build: gathering
        environment:
            - INFLUXDB_HOST=influxdb
            - INFLUXDB_USER
            - INFLUXDB_PASS
            - INFLUXDB_DB
        volumes:
            - ./gathering/:/home/py/gathering
volumes:
    grafana-volume:
    influxdb-volume:
