global:
  scrape_interval:     2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'spring-boot-metrics'

    scrape_interval: 2s
    scrape_timeout: 1s
    metrics_path: '/prometheus'

    static_configs:
     - targets: ['172.17.42.1:8080']
